# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Starting training job on SageMaker"
  build:
    commands:
      # Start SageMaker training job
      - aws sagemaker create-training-job --cli-input-json file://training-job-config.json
      - aws sagemaker wait training-job-completed-or-stopped --training-job-name sagemaker-training-job
  post_build:
    commands:
      # Deploy the trained model to an endpoint
      - python deploy.py
artifacts:
  files:
    - '**/*'
  discard-paths: yes
